//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
  Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "transaction_logs")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: i32,
  pub gateway: String,
  pub transaction_date: DateTime,
  pub account_number: String,
  pub sub_account: Option<String>,
  pub transfer_amount: i64,
  pub accumulated: i64,
  pub code: Option<String>,
  pub content: String,
  pub reference_code: Option<String>,
  pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
