//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
  Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "transactions")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i32,
  pub amount: i64,
  pub created_at: DateTime,
  pub assignment_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::fees_room_assignment::Entity",
    from = "Column::AssignmentId",
    to = "super::fees_room_assignment::Column::AssignmentId",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  FeesRoomAssignment,
}

impl Related<super::fees_room_assignment::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::FeesRoomAssignment.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
