//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "fees")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i32,
  pub name: String,
  pub amount: i64,
  pub is_required: bool,
  pub created_at: Date,
  pub due_date: Date,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::fees_room::Entity")]
  FeesRoom,
  #[sea_orm(has_many = "super::transactions::Entity")]
  Transactions,
}

impl Related<super::fees_room::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::FeesRoom.def()
  }
}

impl Related<super::transactions::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Transactions.def()
  }
}

impl Related<super::rooms::Entity> for Entity {
  fn to() -> RelationDef {
    super::fees_room::Relation::Rooms.def()
  }
  fn via() -> Option<RelationDef> {
    Some(super::fees_room::Relation::Fees.def().rev())
  }
}

impl ActiveModelBehavior for ActiveModel {}
