//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub mod prelude;

pub mod fees;
pub mod fees_room;
pub mod password_recovery_requests;
pub mod rooms;
pub mod sea_orm_active_enums;
pub mod transactions;
pub mod users;
