//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub mod prelude;

pub mod fees;
pub mod fees_room_assignment;
pub mod notifications;
pub mod rooms;
pub mod sea_orm_active_enums;
pub mod users;
