//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub use super::fees::Entity as Fees;
pub use super::fees_room_assignment::Entity as FeesRoomAssignment;
pub use super::notifications::Entity as Notifications;
pub use super::rooms::Entity as Rooms;
pub use super::users::Entity as Users;
