//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "rooms")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub room_number: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::fees_room::Entity")]
  FeesRoom,
  #[sea_orm(has_many = "super::room_tenant::Entity")]
  RoomTenant,
}

impl Related<super::fees_room::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::FeesRoom.def()
  }
}

impl Related<super::room_tenant::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::RoomTenant.def()
  }
}

impl Related<super::fees::Entity> for Entity {
  fn to() -> RelationDef {
    super::fees_room::Relation::Fees.def()
  }
  fn via() -> Option<RelationDef> {
    Some(super::fees_room::Relation::Rooms.def().rev())
  }
}

impl Related<super::users::Entity> for Entity {
  fn to() -> RelationDef {
    super::room_tenant::Relation::Users.def()
  }
  fn via() -> Option<RelationDef> {
    Some(super::room_tenant::Relation::Rooms.def().rev())
  }
}

impl ActiveModelBehavior for ActiveModel {}
